'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Profy
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")>  _
    Partial Friend NotInheritable Class ProfySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As ProfySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ProfySettings()),ProfySettings)
        
        Public Shared ReadOnly Property [Default]() As ProfySettings
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AmountPrice() As String
            Get
                Return CType(Me("AmountPrice"),String)
            End Get
            Set
                Me("AmountPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AmountDec() As String
            Get
                Return CType(Me("AmountDec"),String)
            End Get
            Set
                Me("AmountDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BuyPrice() As String
            Get
                Return CType(Me("BuyPrice"),String)
            End Get
            Set
                Me("BuyPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BuyDec() As String
            Get
                Return CType(Me("BuyDec"),String)
            End Get
            Set
                Me("BuyDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SellPrice() As String
            Get
                Return CType(Me("SellPrice"),String)
            End Get
            Set
                Me("SellPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SellDec() As String
            Get
                Return CType(Me("SellDec"),String)
            End Get
            Set
                Me("SellDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FeePrice() As String
            Get
                Return CType(Me("FeePrice"),String)
            End Get
            Set
                Me("FeePrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FeeDec() As String
            Get
                Return CType(Me("FeeDec"),String)
            End Get
            Set
                Me("FeeDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProfitPrice() As String
            Get
                Return CType(Me("ProfitPrice"),String)
            End Get
            Set
                Me("ProfitPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProfitDec() As String
            Get
                Return CType(Me("ProfitDec"),String)
            End Get
            Set
                Me("ProfitDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property IncomePrice() As String
            Get
                Return CType(Me("IncomePrice"),String)
            End Get
            Set
                Me("IncomePrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property IncomeDec() As String
            Get
                Return CType(Me("IncomeDec"),String)
            End Get
            Set
                Me("IncomeDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DesiredProfitPrice() As String
            Get
                Return CType(Me("DesiredProfitPrice"),String)
            End Get
            Set
                Me("DesiredProfitPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DesiredProfitDec() As String
            Get
                Return CType(Me("DesiredProfitDec"),String)
            End Get
            Set
                Me("DesiredProfitDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DesiredIncomePrice() As String
            Get
                Return CType(Me("DesiredIncomePrice"),String)
            End Get
            Set
                Me("DesiredIncomePrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DesiredIncomeDec() As String
            Get
                Return CType(Me("DesiredIncomeDec"),String)
            End Get
            Set
                Me("DesiredIncomeDec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SellAtPrice() As String
            Get
                Return CType(Me("SellAtPrice"),String)
            End Get
            Set
                Me("SellAtPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SellAtDec() As String
            Get
                Return CType(Me("SellAtDec"),String)
            End Get
            Set
                Me("SellAtDec") = value
            End Set
        End Property
    End Class
End Namespace
